#wyklad
x1<-rnorm(31,mean=12,sd=3)
d<-c("maly","przecietny","duzy")
x1[x1>15]<-"duzy"
x1[x1<9]<-"maly"
x1[x1>=9&&x1<=15]<-"przecietny"

probna<-matrix(,3,2)
probna[1,1:2]<-c(2,5)
probna[2,1:2]<-c(3,1)
probna[3,1:2]<-c(4,0)
probna
rownames(probna)<-c("gorny","srodkowy","dolny")
colnames(probna)<-c("lewa","prawa")
##
probna[2,]

##
matrix1<-matrix(1:4,2,2)
matrix2<-matrix(4:8,2,2)
matrix1*matrix2
matrix1%*%matrix2
##
odwrocona<-t(probna)
solve()
det(matrix1)
###
dowolna_lista<-list("wektor1"<-c(T,T,F,T,F),"wektor2"<-c("ddd","qq","ooo"),"macierz"<-matrix(1:4,2,2))
dowolna_lista